### PR TITLE
Specialize `Kokkos::reduction_identity` for `AmrTag`

### LINKED ISSUE #1274: Problem with `ScatterMax` and `AmrTag` enums
@bprather came across this during the developer meeting with some combination of kokkos/backends where the `ScatterMax` reduction doesn't know what to do with the `AmrTag` enum. If I remember correctly a quick fix was to cast to an int for the reduction, and cast back to `AmrTag`s after.

Possibly related to the Cuda/OpenMP kokkos backend combination from Phillip Edelman:

```
    292    /tmp/pedelmann/spack-stage/spack-stage-parthenon-25.05-7kyih2b6xi2vtcjbzh4xqsqym4qcekhc/spack-src/src/parthenon_array_generic.hpp:226:34:   required from 'aut
            o parthenon::ParArrayGeneric<Data, State, <template-parameter-1-3> >::ToScatterView() [with Op = Kokkos::Experimental::ScatterMax; Data = Kokkos::View<parthen
            on::AmrTag*, Kokkos::LayoutRight, Kokkos::HostSpace>; State = parthenon::empty_state_t; <template-parameter-1-3> = int]'
     293      226 |     return Kokkos::Experimental::ScatterView<data_type, layout, exec_space, Op>(data_);
     294          |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     295    /tmp/pedelmann/spack-stage/spack-stage-parthenon-25.05-7kyih2b6xi2vtcjbzh4xqsqym4qcekhc/spack-src/src/amr_criteria/refinement_package.cpp:115:79:   required f
            rom here
     296      115 |   auto scatter_tags = amr_tags.ToScatterView<Kokkos::Experimental::ScatterMax>();
     297          |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
  >> 298    /home/pedelmann/local/spack/opt/spack/linux-skylake/kokkos-4.6.01-asyrki2oxe22qivmdqbp33qopd75blzl/include/Kokkos_ScatterView.hpp:430:47: error: incomplete ty
            pe 'Kokkos::reduction_identity<parthenon::AmrTag>' used in nested name specifier
     299      430 |     value = reduction_identity<ValueType>::max();
     300          |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
     301    [ 96%] Building CXX object src/CMakeFiles/parthenon.dir/globals.cpp.o
```

### PR DESCRIPTION
**Pull request by acreyes**
## PR Summary

Provides a specialization for `parthenon::AmrTag` needed in the non-atomic `ScatterView`s used in the `MeshData` amr criteria. This would only show up when building with the openMP backend in Kokkos.

addresses #1274 

## PR Checklist

- [ ] Code passes cpplint
- [ ] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Code is formatted
- [ ] Changes are summarized in CHANGELOG.md
- [ ] Change is breaking (API, behavior, ...)
  - [ ] Change is *additionally* added to CHANGELOG.md in the breaking section
  - [ ] PR is marked as breaking
  - [ ] Short summary API changes at the top of the PR (plus optionally with an automated update/fix script)
- [ ] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [ ] Docs build
- [ ] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Review by Yurlungur — APPROVED** [review]
Nice fix!

File: src/amr_criteria/refinement_package.hpp [hunk 1]
```diff
@@ -53,5 +55,13 @@ void SecondDerivative(const AMRBounds &bnds, MeshData<Real> *md, const std::stri
 } // namespace Refinement
 
 } // namespace parthenon
+namespace Kokkos {
+template <>
+struct reduction_identity<parthenon::AmrTag> {
+  using AmrTag = parthenon::AmrTag;
+  KOKKOS_FORCEINLINE_FUNCTION constexpr static AmrTag max() { return AmrTag::refine; }
+  KOKKOS_FORCEINLINE_FUNCTION constexpr static AmrTag min() { return AmrTag::derefine; }
```
Comment (lroberts36) [inline src/amr_criteria/refinement_package.hpp]: I think I am be confused about how `Kokkos::reduction_identity<T>` works. I thought it was supposed to provide the identity for a given operation, so in the case of `max()` for `AmrTag` I would have thought the identity would be `AmrTag::derefine` since
```c++
max(AmrTag::derefine, AmrTag::derefine) = AmrTag::derefine;
max(AmrTag::derefine, AmrTag::same) = AmrTag::same;
max(AmrTag::derefine, AmrTag::refine) = AmrTag::refine;
```
given that `AmrTag::derefine -> -1`, etc. in the enum.

Comment (lroberts36) [reply src/amr_criteria/refinement_package.hpp]: I am probably just missing something obvious though.

Comment (acreyes) [reply src/amr_criteria/refinement_package.hpp]: you're right, I was following the specialization for `reduction_identity<int>` and they use 
```
max() {return INT_MIN;}
min() {return INT_MAX;}
```
and I must have been looking at it cross eyed: https://github.com/kokkos/kokkos/blob/develop/core/src/Kokkos_ReductionIdentity.hpp#L150

**Review by lroberts36 — APPROVED** [review]
LGTM

**Comment by tukss** [comment]
I can confirm this fixes my build issues with kokkos+openmp and parthenon. Thanks for the quick fix!!

**Comment by pgrete** [comment]
Thanks for the report and the nice and clean fix.
I wonder if this points towards adding a build test with the OpenMP backend.

**Comment by pgrete** [comment]
@par-hermes format

**Comment by pgrete** [comment]
@acreyes IIRC the extended pipeline do not work on forks.
We could either force merge (trusting that this minor fix does not break tests in the extended suite) or move the changes to a branch of the main repo.

**Comment by Yurlungur** [comment]
FWIW @acreyes is now allowed to push directly to the main repo. I added him as a contributor.

**Comment by acreyes** [comment]
> FWIW @acreyes is now allowed to push directly to the main repo. I added him as a contributor.

I'll merge into a main repo branch and open a new PR
