### PR TITLE
Fix initital timestep calculation for `MeshData` functions

### LINKED ISSUE #401: Initial timestep not calculated for `MeshData` based functions
For apps using `MeshData`based `EstimateTimestep` functions (rather than `MeshBlockData` based) the initial timestep is not calculated.

### PR DESCRIPTION
**Pull request by pgrete**
## PR Summary

Takes `MeshData` based functions into account when calculating the first timestep.

Fixes #401 

## PR Checklist

- [x] Code passes cpplint
- [does not apply] New features are documented.
- [?] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Code is formatted
- [x] Changes are summarized in CHANGELOG.md

This "bug" made me wonder if we should split/duplicate/extend the advection example so that we test both the `MeshData` and `MeshBlockData` based machinery in Parthenon.
Maybe @jlippuner planned proxy app (going for AMR performance with small MeshBlocks where we definitely need the `MeshData` functions could exclusively use the `MeshData` framework and we keep the current advection example to only use the `MeshBlockData` based interface.

Any opinions?

### CODE REVIEW

**Review by Yurlungur — APPROVED** [review]
Thanks for this, @pgrete . I do think it would be a good idea to split the `advection` example in the way you suggest.

But one thing I don't understand... shouldn't the `dt` from `MeshData` be the same as the minimum `dt` over `MeshBlocks`s? Also, should we perhaps offer the ability to only use `MeshData` or only use `MeshBlockData` for this loop, to potentially save some kernel launches?

File: src/interface/mesh_data.hpp [hunk 1]
```diff
@@ -88,7 +89,7 @@ class MeshData {
 
   void SetAllowedDt(const Real dt) const {
```
Comment (JoshuaSBrown) [inline src/interface/mesh_data.hpp:90]: I feel like the name of this method needs to be changed because it is no longer just a set. E.g. ConsolidateAllowedDt though even that is not entirely clear either.

**Review by JoshuaSBrown — APPROVED** [review]
Other than possibly adjusting the name of the set method this looks good to me. Thanks for fixing this!

File: src/interface/mesh_data.hpp (hunk 1 above)
Comment (pgrete) [reply src/interface/mesh_data.hpp:90]: I agree (and would even go further as some naming doesn't seem to match the implementation any more).
Should I fix this here or in a separate PR?

**Comment by pgrete** [comment]
> But one thing I don't understand... shouldn't the `dt` from `MeshData` be the same as the minimum `dt` over `MeshBlocks`s?

I assume that you're referring to
```diff
    for (const auto &pbd : block_data_) {
-      pbd->SetAllowedDt(dt);
+      pbd->SetAllowedDt(std::min(dt, pbd->GetBlockPointer()->NewDt()));
    }
  }
```

This is required because the default `dt` is the `numeric_limit<Real>`, thus, if the existing new timestep contained in `NewDt()` is not honored then it would be set to the max value (effectively ignoring the new one).

> Also, should we perhaps offer the ability to only use `MeshData` or only use `MeshBlockData` for this loop, to potentially save some kernel launches?

Are kernel launches here refer to function calls? If a function is not enrolled then nothing should happen (though I'm not sure if the compiler is smart enough to skip the entire loop completely in that case).

File: src/interface/mesh_data.hpp (hunk 1 above)
Comment (JoshuaSBrown) [reply src/interface/mesh_data.hpp:90]: I'm fine if you merge and open a WIP pr to fix it.

Comment (pgrete) [reply src/interface/mesh_data.hpp:90]: Sounds good. I'll merge then (one thing off the table).
