### PR TITLE
Fix regional dependencies for sub-`TaskList`s and make solvers work for abitrary partitioning

### LINKED ISSUE #1125: `TaskQualifier::*_sync` does not work for iterative task lists
When `TaskRegion::BuildGraph` is called, it connects regional tasks across all of the task lists in `TaskRegion::task_lists` but does not appear to do anything with the task lists contained in `TaskList::sublists`. As a result, the BiCGSTAB solver hangs for more than one partition since the residual is zeroed out by one task for a reduction before other tasks have the chance to check the residual in their completion task in the previous iteration.

I will try to take a look at how to fix this next week.

### PR DESCRIPTION
**Pull request by lroberts36**
## PR Summary
Currently, sublists of `TaskList`s do not have their regional dependencies set correctly. This results in the bug described in #1125. This PR changes `TaskRegion::BuildGraph()` to correctly register regional dependencies among all `TaskList`s and closes #1125. 

Additionally, it takes a second step to make the multigrid solver work when `parthenon/mesh/pack_size != -1` by including "self-communication" between coarse blocks on a finer two-level composite grid and fine leaf blocks on the next coarser two-level composite grid. Although no data is communicated in these communication channels, this introduces a dependency (outside of the tasking framework) that ensures operations on these blocks that are part of multiple gmg levels occur in the correct order.

Getting the multigrid stuff to work was a painful debugging process. As a result, I introduced some capability for more customized naming of tasks and the ability to write task labels to screen as the tasks are called. This turned out to be fairly useful for debugging what was going on.

## PR Checklist

- [x] Code passes cpplint
- [ ] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Code is formatted
- [x] Changes are summarized in CHANGELOG.md
- [ ] Change is breaking (API, behavior, ...)
  - [ ] Change is *additionally* added to CHANGELOG.md in the breaking section
  - [ ] PR is marked as breaking
  - [ ] Short summary API changes at the top of the PR (plus optionally with an automated update/fix script)
- [x] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [ ] Docs build
- [ ] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Review by Yurlungur — COMMENTED** [review]
I really feel like @jdolence should look at this one.

File: src/bvals/comms/bnd_info.cpp [hunk 1]
```diff
@@ -177,7 +177,7 @@ CalcIndices(const NeighborBlock &nb, MeshBlock *pmb,
                                 (neighbor_bounds[dir].e - neighbor_bounds[dir].s + 1);
         s[dir] += nb.origin_loc.l(dir) % 2 == 1 ? extra_zones - interior_offset : 0;
         e[dir] -= nb.origin_loc.l(dir) % 2 == 0 ? extra_zones - interior_offset : 0;
-        if (ir_type == IndexRangeType::InteriorSend) {
+        if (ir_type == IndexRangeType::InteriorSend && !prores) {
```
Comment (lroberts36) [inline src/bvals/comms/bnd_info.cpp:180]: Changes to `CalcIndices` are required since we are actually passing the correct neighbor information in `GetInterior*`.

File: src/bvals/comms/bnd_info.hpp [hunk 2]
```diff
@@ -59,6 +59,7 @@ struct BndInfo {
   bool allocated = true;
   bool buf_allocated = true;
   int alloc_status;
+  bool same_to_same = false;
```
Comment (lroberts36) [inline src/bvals/comms/bnd_info.hpp:62]: This flag denotes that this buffer represents a communication from this block to itself and that the buffer does not need to be filled (a message just needs to be sent).

File: src/bvals/comms/bvals_utils.hpp [hunk 3]
```diff
@@ -35,22 +35,35 @@
...
+                                   BoundaryType btype) {
   const int sender_id = pmb->gid;
   const int receiver_id = nb.gid;
   const int location_idx = nb.offsets.GetIdx();
-  return {sender_id, receiver_id, pcv->label(), location_idx};
+  int other = (nb.gid == pmb->gid && (btype == BoundaryType::gmg_restrict_recv ||
+                                      btype == BoundaryType::gmg_restrict_send))
+                  ? 1
+                  : 0;
+  return {sender_id, receiver_id, pcv->label(), location_idx, other};
```
Comment (lroberts36) [inline src/bvals/comms/bvals_utils.hpp:53]: Add more information to the communication key so that we can represent same-to-same restriction and same-to-same prolongation as different channels.

File: src/tasks/tasks.hpp [hunk 4]
```diff
@@ -106,7 +113,11 @@ class Task {
   template <typename TID>
   Task(TID &&dep, const std::string &label, const std::function<TaskStatus()> &func,
        std::pair<int, int> limits = {1, 1})
-      : label_(label), f(func), exec_limits(limits) {
+      : Task(std::forward<TID>(dep), label, 0, func, limits) {}
+  template <typename TID>
+  Task(TID &&dep, const std::string &label, int verbose_level,
+       const std::function<TaskStatus()> &func, std::pair<int, int> limits = {1, 1})
+      : label_(label), verbose_level_(verbose_level), f(func), exec_limits(limits) {
```
Comment (lroberts36) [inline src/tasks/tasks.hpp:121]: Add verbosity flag to tasks, if `verbose_level_ > 0` the task will print its name out to stdout before starting the task. Useful for debugging.

File: src/tasks/tasks.hpp [hunk 5]
```diff
@@ -270,18 +283,23 @@ class TaskList {
...
-      return AddTaskImpl(tq, dep, {}, std::forward<Arg1>(arg1),
+      return AddTaskImpl(tq, dep, {}, 0, std::forward<Arg1>(arg1),
                          std::forward<Args>(args)...);
     } else if constexpr (std::is_convertible<Arg1, std::string>::value) {
-      return AddTaskImpl(tq, dep, std::forward<Arg1>(arg1), std::forward<Args>(args)...);
+      return AddTaskImpl(tq, dep, std::forward<Arg1>(arg1), 0,
+                         std::forward<Args>(args)...);
+    } else if constexpr (is_tuple_t<Arg1>::value) {
+      return AddTaskImpl(tq, dep, std::get<0>(arg1), std::get<1>(arg1), std::get<2>(arg1),
+                         std::forward<Args>(args)...);
```
Comment (lroberts36) [inline src/tasks/tasks.hpp:296]: Allow passing a `tuple` containing the name of the task, the verbosity level of the task, and the task function itself. Allows easy print out of the order in which tasks are run.

File: src/tasks/tasks.hpp [hunk 6]
```diff
@@ -413,6 +431,12 @@ class TaskList {
     return WriteTaskGraph(stream, tasks);
   }
 
+  std::vector<TaskList *> GetAllTaskLists() {
+    std::vector<TaskList *> list;
+    GetAllTaskListsInternal(list);
+    return list;
+  }
```
Comment (lroberts36) [inline src/tasks/tasks.hpp:441]: Necessary for linking regional tasks in iterative task lists.

File: src/bvals/comms/bnd_info.cpp [hunk 7]
```diff
@@ -330,6 +331,8 @@ BndInfo BndInfo::GetSetBndInfo(MeshBlock *pmb, const NeighborBlock &nb,
   } else if (buf_state == BufferState::received_null) {
     out.buf_allocated = false;
   } else {
+    printf("%i -> %i (Set %s) is in state %i.\n", nb.gid, pmb->gid, v->label().c_str(),
+           buf_state);
```
Comment (Yurlungur) [inline src/bvals/comms/bnd_info.cpp]: Should you also print MPI rank?

File: src/interface/mesh_data.hpp [hunk 8]
```diff
@@ -290,6 +290,14 @@ class MeshData {
 
   const auto &GetAllBlockData() const { return block_data_; }
 
+  bool ContainsGid(int gid) const {
```
Comment (pdmullen) [inline src/interface/mesh_data.hpp:293]: Any concern about stale `gid`s  here (c.f., https://github.com/parthenon-hpc-lab/parthenon/pull/1010)?

File: src/tasks/tasks.hpp [hunk 9]
```diff
@@ -120,6 +131,9 @@ class Task {
 
   TaskStatus operator()() {
     auto status = f();
+    if (verbose_level_ > 0)
+      std::cout << label_ << " [status = " << static_cast<int>(status) << "]"
+                << std::endl;
```
Comment (Yurlungur) [inline src/tasks/tasks.hpp]: Should these include MPI rank? Also `printf` more than stream is probably better because with MPI streams can get muddled. Better to send a whole string to `cout` at once.

**Review by Yurlungur — APPROVED** [review]
Very minor nitpicks on the debugging code. Otherwise LGTM.

File: src/tasks/tasks.hpp (hunk 4 above)
Comment (pdmullen) [reply src/tasks/tasks.hpp:121]: This is a useful feature.  I wonder if the verbosity should be blanket applied to all tasks based off a `verbose` flag set in `pin`, rather than enrolled via each `AddTask`?

EDIT: this proposal could actually be handled via the downstream app

File: tst/regression/test_suites/poisson_gmg/parthinput.poisson [hunk 10]
```diff
@@ -17,6 +17,7 @@ problem_id = poisson
 <parthenon/mesh>
 refinement = static
 multigrid = true 
+pack_size = 1
```
Comment (pdmullen) [inline tst/regression/test_suites/poisson_gmg/parthinput.poisson:20]: excellent

**Review by pdmullen — APPROVED** [review]
LGTM! I have tested this in a downstream app invoking iterative tasking.  This MR *fixes* (1) hangs and (2) undefined behavior when invoking `pack_size = 1` that currently exist with `parthenon/develop`.

File: src/bvals/comms/bnd_info.cpp (hunk 7 above)
Comment (lroberts36) [reply src/bvals/comms/bnd_info.cpp]: yeah, we could include that.

File: src/tasks/tasks.hpp (hunk 9 above)
Comment (lroberts36) [reply src/tasks/tasks.hpp]: sure, that is a valid concern. I will include rank as well.

File: src/interface/mesh_data.hpp (hunk 8 above)
Comment (lroberts36) [reply src/interface/mesh_data.hpp:293]: I don't think so, since the `MeshData` should be cleared and recreated on remeshing. This doesn't rely on the gids of the variables themselves.

File: src/tasks/tasks.hpp (hunk 4 above)
Comment (lroberts36) [reply src/tasks/tasks.hpp:121]: I agree that would be nice, but I think that it requires a bit of threading to make it work (since the tasking stuff doesn't directly access `pin` currently). I would leave this for a future PR. 

In practice, I just manually comment out the `verbose_level_ > 0` test and recompile if I want to see everything...

File: src/bvals/comms/bnd_info.cpp (hunk 7 above)
Comment (lroberts36) [reply src/bvals/comms/bnd_info.cpp]: done

File: src/tasks/tasks.hpp (hunk 9 above)
Comment (lroberts36) [reply src/tasks/tasks.hpp]: done
