### PR TITLE
Changed lambda to for-loop to work around gcc7.3.0

### LINKED ISSUE #523: Internal Compiler Error GCC 7.3.0
Compiling with GCC 7.3.0 leads to this compiler error
```
mnt/home/glinesfo/code/parthenon/parthenon/src/outputs/parthenon_hdf5.cpp: In instantiation of ‘parthenon::PHDF5Output::WriteOutputFileImpl(parthenon::Mesh*, parthenon::ParameterInput*, parthenon::SimTime*)::<lambda(bool)> [with bool WRITE_SINGLE_PRECISION = true]’:                                                
/mnt/home/glinesfo/code/parthenon/parthenon/src/outputs/parthenon_hdf5.cpp:649:81:   required from ‘struct parthenon::PHDF5Output::WriteOutputFileImpl(parthenon::Mesh*, parthenon::ParameterInput*, parthenon::SimTime*) [with bool WRITE_SINGLE_PRECISION = true]::<lambda(bool)>’                                       
/mnt/home/glinesfo/code/parthenon/parthenon/src/outputs/parthenon_hdf5.cpp:619:6:   required from ‘void parthenon::PHDF5Output::WriteOutputFileImpl(parthenon::Mesh*, parthenon::ParameterInput*, parthenon::SimTime*) [with bool WRITE_SINGLE_PRECISION = true]’                                                          
/mnt/home/glinesfo/code/parthenon/parthenon/src/outputs/parthenon_hdf5.cpp:335:46:   required from here                                                                                                                                                                                                                    
/mnt/home/glinesfo/code/parthenon/parthenon/src/outputs/parthenon_hdf5.cpp:624:36: internal compiler error: in maybe_undo_parenthesized_ref, at cp/semantics.c:1705                                                                                                                                                        
     std::vector<Real> loc_x((nx1 + offset) * num_blocks_local);                                                                                                                                                                                                                                                           
                             ~~~~~~~^~~~~~~~~        
```
This might be related to this bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=882855 which was encountered in a different context in Kokkos: https://github.com/kokkos/kokkos-kernels/issues/349.

These are the  offending lines in `parthenon_hdf5.cpp`
```
std::vector<Real> loc_x((nx1 + offset) * num_blocks_local);
std::vector<Real> loc_y((nx2 + offset) * num_blocks_local);
std::vector<Real> loc_z((nx3 + offset) * num_blocks_local);
```
I've tried adding parenthesis, computing the offset on a separate line, changing the `const` on `nx1`,`offset`, and `num_blocks_local`, capturing `nx1` and `num_blocks_local` by value, nothing works. GCC 7.3.0 just doesn't want to add together `nx1 + offset`. Any thoughts or suggestions?

### PR DESCRIPTION
**Pull request by forrestglines**
## PR Summary

Works around the bug in GCC 7.3.0 encountered in issue #523 

## PR Checklist

- [ ] Code passes cpplint
- [x] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Code is formatted
- [x] Changes are summarized in CHANGELOG.md
- [ ] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [ ] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Comment by forrestglines** [comment]
@par-hermes format

**Review by Yurlungur — APPROVED** [review]
Nice fix. Strange bug but glad its resolved.

File: src/outputs/parthenon_hdf5.cpp [hunk 1]
```diff
@@ -616,7 +616,8 @@ void PHDF5Output::WriteOutputFileImpl(Mesh *pm, ParameterInput *pin, SimTime *tm
     }
   } // Block section
 
-  auto WriteLocations = [&](bool face) {
+  // Write mesh coordinates to file
+  for (const bool face : {true, false}) {
```
Comment (JoshuaSBrown) [inline src/outputs/parthenon_hdf5.cpp:622]: I didn't know you could do this nice, it's almost pythonic.

**Review by JoshuaSBrown — APPROVED** [review]
