### PR TITLE
Fix MPI tag creation

### LINKED ISSUE #660: Are we properly incrementing `phys_id`?
I dug deeper into the issue that was raised during yesterday's call.

Here's what I found so far:
In the original Athena++ implementation, the physical ids for "standard" variables (e.g., hydro or b-fields) were implicitly updated in the constructor of various "physics", e.g., in `meshblock.cpp`
```c++
    phydro = new Hydro(this, pin);
    pbval->AdvanceCounterPhysID(HydroBoundaryVariable::max_phys_id);
  if (MAGNETIC_FIELDS_ENABLED) {
    pfield = new Field(this, pin);
    pbval->AdvanceCounterPhysID(FaceCenteredBoundaryVariable::max_phys_id);
  }
```
the `Hydro` and `Field` constructors would use the *current* `next_phys_id` (private var of the `MeshBlock`) for setting up the boundary variables.
The ids are *not* updated when they are assigned to the bvars, but afterwards manually incremented (by some const. max value).

*We don't call `AdvanceCounterPhysID` anywhere...

At the `Mesh` level Athena++ also has (and calls) `ReserveTagPhysIDs` in order to set a mesh level id (mesh private `next_phys_id`) so that other, extra  physics that need boundary comm start with a proper offset for the tags.

Given that from a Parthenon point of view everything is "extra" (as in separate packages), we don't need two separate functions, but need to ensure that we always advance the id for all kind of `Variables`.

Some dirty debugging in Parthenon with 
```diff
diff --git a/src/bvals/cc/bvals_cc.cpp b/src/bvals/cc/bvals_cc.cpp
index a22b0ed0..04bfc526 100644
--- a/src/bvals/cc/bvals_cc.cpp
+++ b/src/bvals/cc/bvals_cc.cpp
@@ -66,6 +66,7 @@ CellCenteredBoundaryVariable::CellCenteredBoundaryVariable(std::weak_ptr<MeshBlo
   // KGF: dead code, leaving for now:
   // cc_phys_id_ = pmb->pbval->ReserveTagVariableIDs(1);
   cc_phys_id_ = pmb.lock()->pbval->bvars_next_phys_id_;
+  std::cout << label << " uses id " << cc_phys_id_ << std::endl;
 #endif
   if (pmy_mesh_->multilevel) { // SMR or AMR
     InitBoundaryData(bd_var_flcor_, BoundaryQuantity::cc_flcor);
```
with the advection example and `Advection/num_vars=2`:
```
advected uses id 1
advected_1 uses id 1
advected uses id 1
advected_1 uses id 1
advected uses id 1
advected_1 uses id 1
...
```
not great.

I assume that this hasn't caused any bugs because the packing machinery has mostly been used with a single pack per rank and everything was well ordered (so even if two messages were send with the same tag for two different variables the receiving function were also in the same order).
This would also be connected to the intermittent MPI errors that Jonas saw when he implemented sparse variables.

A first fix 
```diff
diff --git a/src/bvals/cc/bvals_cc.cpp b/src/bvals/cc/bvals_cc.cpp
index a22b0ed0..491e6e79 100644
--- a/src/bvals/cc/bvals_cc.cpp
+++ b/src/bvals/cc/bvals_cc.cpp
@@ -63,14 +63,14 @@ CellCenteredBoundaryVariable::CellCenteredBoundaryVariable(std::weak_ptr<MeshBlo
   InitBoundaryData(bd_var_, BoundaryQuantity::cc);
 
 #ifdef MPI_PARALLEL
-  // KGF: dead code, leaving for now:
-  // cc_phys_id_ = pmb->pbval->ReserveTagVariableIDs(1);
-  cc_phys_id_ = pmb.lock()->pbval->bvars_next_phys_id_;
+  cc_phys_id_ = pmb.lock()->pbval->AdvanceCounterPhysID(1);
+  std::cout << label << " uses id " << cc_phys_id_ << std::endl;
 #endif
   if (pmy_mesh_->multilevel) { // SMR or AMR
     InitBoundaryData(bd_var_flcor_, BoundaryQuantity::cc_flcor);
 #ifdef MPI_PARALLEL
-    cc_flx_phys_id_ = cc_phys_id_ + 1;
+    cc_flx_phys_id_ = pmb.lock()->pbval->AdvanceCounterPhysID(1);
+    std::cout << label << " flx uses id " << cc_flx_phys_id_ << std::endl;
 #endif
   }
 }
```
resulting in some interesting behavior:
```
advected_1 uses id 1
advected_1 flx uses id 2
advected uses id 3
advected flx uses id 4
advected_1 uses id 1
advected_1 flx uses id 2
advected uses id 3
advected flx uses id 4
cycle=3 time=5.2734375000000003e-03 dt=1.7578125000000000e-03 zone-cycles/wsec_step=5.02e+06 wsec_total=2.20e-02 wsec_step=4.49e-03 zone-cycles/wsec=3.50e+06 wsec_AMR=1.96e-03
-------------- New Mesh structure after (de)refinement -------------
Root grid = 4 x 4 x 1 MeshBlocks
Total number of MeshBlocks = 94
Number of physical refinement levels = 2
Number of logical  refinement levels = 4
  Physical level = 0 (logical level = 2): 3 MeshBlocks, cost = 3
  Physical level = 1 (logical level = 3): 39 MeshBlocks, cost = 39
  Physical level = 2 (logical level = 4): 52 MeshBlocks, cost = 52
--------------------------------------------------------------------
advected_1 uses id 5
advected_1 flx uses id 6
advected uses id 7
advected flx uses id 8
advected_1 uses id 9
advected_1 flx uses id 10
advected uses id 11
advected flx uses id 12
```
I don't understand yet where the ids >4 are coming from.

### PR DESCRIPTION
**Pull request by pgrete**
## PR Summary

Fixes #660 

## PR Checklist

- [x] Code passes cpplint
- [ ] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Code is formatted
- [x] Changes are summarized in CHANGELOG.md
- [ ] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [ ] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Review by Yurlungur — COMMENTED** [review]
Overall this looks right to me. At some point, I do thing we should rethink how we do the boundary variables more deeply than this. But this at least gets us to a "correct" implementation.

Thanks for digging in to this!

**Comment by lroberts36** [comment]
Doesn't this still leave open the possibility that the `phyd_id` overruns the five bits reserved for it in `BoundaryBase::CreateBvalsMPITag`? A check for this should at least be added as noted in the TODO at https://github.com/lanl/parthenon/blob/1d72227179ce2e34dcba9736587c0f167326d32b/src/bvals/bvals.cpp#L136.

**Comment by pgrete** [comment]
> Doesn't this still leave open the possibility that the `phyd_id` overruns the five bits reserved for it in `BoundaryBase::CreateBvalsMPITag`? A check for this should at least be added as noted in the TODO at
> 
> https://github.com/lanl/parthenon/blob/1d72227179ce2e34dcba9736587c0f167326d32b/src/bvals/bvals.cpp#L136
> .

Good point. I added an appropriate check with error message.

**Comment by pgrete** [comment]
While going through this PR again,I think this needs additional input from @brryan 

For `BoundarySwarms`, the id is always 0 (which is technically reserved for AMR)
https://github.com/lanl/parthenon/blob/97f181b79f145946372a64b9ba2e0382601df632/src/bvals/bvals.hpp#L125
as also set here (for `BoundarySwarms`)
https://github.com/lanl/parthenon/blob/97f181b79f145946372a64b9ba2e0382601df632/src/bvals/bvals.cpp#L197
but
https://github.com/lanl/parthenon/pull/661/files#diff-05bb8e353c4c92e6744e925fad3f395d17ea4e7a98f61978e183873d09e5b11c
actually uses the `pbval` pointer and not the `pbswarm` pointer.

So it looks to me that some things are not properly aligned.
Any comments (also from others)?

**Comment by Yurlungur** [comment]
Is the swarm thing not automatically fixed by just setting a bit for swarms? Or alternatively, making a new communicator for swarms?

**Comment by pgrete** [comment]
> Is the swarm thing not automatically fixed by just setting a bit for swarms? Or alternatively, making a new communicator for swarms?

Yes, there are various straightforward fixes. I think it'd make sense to go with the one that @brryan considers most appropriate given the other open PRs -- especially thinking ahead in terms of supporting multiple Swarms.
So I could imagine that a separate communicator would make the most sense.

**Comment by brryan** [comment]
Thanks for pinging me on this -- yes I would imagine this PR would potentially cause issues for swarms. I think @Yurlungur / @pgrete 's solution of one communicator per swarm is a good path forward. Right now all particle variables are always communicated simultaneously so there shouldn't be any additional subtleties to worry about at the moment. I am out of the office this week but I can think through this in detail on Monday. Probably the tracers example with MPI is the best place to test these changes, since that has both cc vars and a swarm, but I don't think that's included in our automated testing currently.

File: src/bvals/bvals_swarm.cpp [hunk 1]
```diff
@@ -41,7 +41,7 @@ namespace parthenon {
 BoundarySwarm::BoundarySwarm(std::weak_ptr<MeshBlock> pmb)
     : bswarm_index(), pmy_block(pmb), pmy_mesh_(pmb.lock()->pmy_mesh) {
 #ifdef MPI_PARALLEL
-  swarm_id_ = pmb.lock()->pbval->bvars_next_phys_id_;
+  swarm_id_ = pmb.lock()->pbval->AdvanceCounterPhysID(1);
```
Comment (brryan) [inline src/bvals/bvals_swarm.cpp]:
```suggestion
  swarm_id_ = pmb.lock()->pbswarm->AdvanceCounterPhysID(1);
```
Yes this is a bug, thanks for noticing this @pgrete!

**Comment by brryan** [comment]
@pgrete Looking at this now, my thinking for moving forward with swarm phys ids is to:

1) change to `pbswarm` in `src/bvals/bvals_swarm.cpp`
2) Use the same logic in `AdvanceCounterPhysId` for swarms as for variables, except have `num_phys` always be `1` i.e. the counter is incremented once per swarm (void argument):
```c++
int BoundarySwarm::AdvanceCounterPhysID() {
#ifdef MPI_PARALLEL
  int start_id = bvars_next_phys_id_;
  bvars_next_phys_id_ += 1;
  PARTHENON_REQUIRE_THROWS(
      bvars_next_phys_id_ < 32,
      "Next phys_id would be >= 32, which is currently not supported as Parthenon only "
      "reserves 5 bits for phys_id. Please open an issue on GitHub if you see this "
      "message to discuss options.")
  return start_id;
#else
  return 0;
#endif
}
```

In this pattern each swarm has a specific `phys_id`. I don't anticipating needing large numbers of swarms so a small byte limit might be fine here. To generalize each swarm could have its own communicator later on. 

One thing this prevents is different communication patterns for different subsets of a swarm's `ParticleVariable`s. We always communicate all `ParticleVariable`s currently and I think this is mostly reasonable but probably could lead to unnecessary communication in some cases. I think, though, that that is an issue best addressed later if necessary (dealing with that would probably necessitate a one-communicator-per-swarm model).

Does that seem reasonable to you? I certainly could be missing something.

**Comment by Yurlungur** [comment]
> @pgrete Looking at this now, my thinking for moving forward with swarm phys ids is to:
> 
>     1. change to `pbswarm` in `src/bvals/bvals_swarm.cpp`
> 
>     2. Use the same logic in `AdvanceCounterPhysId` for swarms as for variables, except have `num_phys` always be `1` i.e. the counter is incremented once per swarm (void argument):
> 
> 
> ```c++
> int BoundarySwarm::AdvanceCounterPhysID() {
> #ifdef MPI_PARALLEL
>   int start_id = bvars_next_phys_id_;
>   bvars_next_phys_id_ += 1;
>   PARTHENON_REQUIRE_THROWS(
>       bvars_next_phys_id_ < 32,
>       "Next phys_id would be >= 32, which is currently not supported as Parthenon only "
>       "reserves 5 bits for phys_id. Please open an issue on GitHub if you see this "
>       "message to discuss options.")
>   return start_id;
> #else
>   return 0;
> #endif
> }
> ```
> 
> In this pattern each swarm has a specific `phys_id`. I don't anticipating needing large numbers of swarms so a small byte limit might be fine here. To generalize each swarm could have its own communicator later on.
> 
> One thing this prevents is different communication patterns for different subsets of a swarm's `ParticleVariable`s. We always communicate all `ParticleVariable`s currently and I think this is mostly reasonable but probably could lead to unnecessary communication in some cases. I think, though, that that is an issue best addressed later if necessary (dealing with that would probably necessitate a one-communicator-per-swarm model).
> 
> Does that seem reasonable to you? I certainly could be missing something.

Won't this fail unless there's a separate communicator for swarms vs grid variables?

**Comment by brryan** [comment]
> Won't this fail unless there's a separate communicator for swarms vs grid variables?

Oh yes you're right... I suppose we now need either (1) a separate communicator for swarms (2) a bit reserved in the tag for swarm vs cc variable

**Comment by Yurlungur** [comment]
I am in favor of a separate communicator for swarms, which frees up more bits for variables in their communicator.

**Comment by pgrete** [comment]
I now added a separate communicator (in addition to the tag fix, which is technically not required [any more]).
However, sth goes wrong and I get a deadlock in Receive. Just replacing the three `MPI_COMM_SWARM` with `MPI_COMM_WORLD` int the `BoundarySwarm::Send` and `BoundarySwarm::Receive` methods makes everything work again.
If anyone has a quick idea about what I'm missing, I'm happy for input.

**Comment by brryan** [comment]
@pgrete Thanks for adding the swarm communicator! Unrelated (or not) I just ran into an issue today with particles hanging with MPI (on my heavily modified branches), I'm guessing due to `Swarm::Receive`. I'll take a look at your branch now and see if I notice anything.

**Comment by pgrete** [comment]
FYI this is now ready for re-review. Everything seems to work as expected now as far as I can tell.

**Comment by pgrete** [comment]
FYI this is now ready for re-review. Everything seems to work as expected now as far as I can tell.

**Comment by pgrete** [comment]
Okay, new problem:
When running with true sparse variables, parthenon segfaults at
```
  /// Repoint vbvar's var_cc array at the current variable
  inline void resetBoundary() { vbvar->var_cc = data; }
```
(or more specifically at the)
```
  operator=(const ParArrayNDGeneric<Data> &t) = default;
```
call inside.

I'm not sure why this is happening (maybe because there's no `data` for true sparse variables to begin with.

Before digging into that, I'm actually wondering, do we still need the `resetBoundary` functionality or is this effectively also dead code? Also a question for @lroberts36

**Comment by lroberts36** [comment]
I was discussing this with @Yurlungur on Monday. It is not clear that the call to `resetBoundary()` in `ResetSendBuffers(...)` does anything. `BndInfo.var` is set directly from the variable (i.e. by `v->data` rather than by `v->vbvar->var_cc`), and I don't see anywhere else that uses `vbvar->var_cc` in the `bvals_in_one` code. Maybe the call to `resetBoundary()` can just be commented out? 

I don't think I will use this functionality in my update to the boundary communication routines.

**Comment by Yurlungur** [comment]
Yeah, I suspect that `resetBoundary()` call is not doing anything. I suggest we remove it and see if that breaks anything.

**Comment by lroberts36** [comment]
Yeah, running the `sparse_advection` regression test with that line commented out succeeds.

**Comment by Yurlungur** [comment]
Sounds like we should just remove that line then.

**Comment by pgrete** [comment]
Interesting, for me this still fails because the `vbvar` is not properly setup anymore (so a call to the block pointer fails).
I think this is related to the updated allocation in this PR (that the bvar allocation now actually takes place in `AllocateFluxesAndBdryVar` and not in the variable constructor).
I'm still investigating.

**Comment by pgrete** [comment]
With respect to whether we need `resetBoundary` or not depends on a basic design decision.
For variables across multiple stages the fluxes and boundary vars are getting reused.
So depending on whether we want to allow for sending data and fluxes from other than the base container we need to repoint the data pointer or not.
AthenaPK currently works under the assumption that only the `base` stage contains data/fluxes to be sent.

**Comment by Yurlungur** [comment]
> AthenaPK currently works under the assumption that only the base stage contains data/fluxes to be sent.

I don't think Phoebus or rage make this assumption. But I think in `pack_in_one`, it should not matter, because we use `restrict_in_one` to do the restriction, right? In which case, the metadata in `vbvar` doesn't participate. Or do we still use per-meshblock restriction?

**Comment by lroberts36** [comment]
Yes, anywhere we are working with `MeshData` instead of `MeshBlock`s I think it is unnecessary.

File: .gitlab-ci.yml [hunk 2]
```diff
@@ -95,7 +95,11 @@ parthenon-cuda-short:
       ../
     - make -j${J} advection-example
     - export OMPI_MCA_mpi_common_cuda_event_max=1000
+    # Run one example with variables
     - ctest -R regression_mpi_test:output_hdf5
+    # and one that uses swarms
+    - make -j${J} particle-leapfrog
+    - ctest -R regression_mpi_test:particle_leapfrog
```
Comment (brryan) [inline .gitlab-ci.yml:102]: Thanks!

**Review by brryan — APPROVED** [review]
LGTM! A long-overdue fix.

**Comment by pgrete** [comment]
Quick update: the fix I tried didn't work after reintroducing the `resetBoundary` calls as now there's a clash between (reused) `bvars` across stages.
I need to further investigate...

**Comment by pgrete** [comment]
@brryan @Yurlungur this is ready for complete re-review now.
I think I got everything (including an index bug that is currently in `develop` and resulted in the pipeline to fail there [1]).
This PR actually fixes an additional bugs around MPI comm (apart from the tags), i.e., the `bval` should now be properly shared among all shallow copies of each `Variable` (originally there were multiple extra copies as the `PARTHENON_REQUIRE` conditional was off).
I can now see how this could have messed up comms in some circumstances.

[1] I think it may be worth to make sure we always trigger the full suite before merging any open PR in the future
[edit] This reminds me that I need to fix/remove the coverage stage as the original sparse PR resulted in the coverage stage taking hours and then timing out [/edit]

**Comment by pgrete** [comment]
Also ping @lroberts36 so that this is ready to be tested against the MPI issue you encountered for the sparse comm.

**Comment by Yurlungur** [comment]
Thanks @pgrete I'll try to look at this today.

? [1] I think it may be worth to make sure we always trigger the full suite before merging any open PR in the future
[edit] This reminds me that I need to fix/remove the coverage stage as the original sparse PR resulted in the coverage stage taking hours and then timing out [/edit]

I think it depends. For infrastructure PRs I think that's for sure. For smaller changes probably not necessary. We can use our judgement.

File: docs/interface/state.md [hunk 3]
```diff
@@ -140,5 +140,8 @@ The overload `Add(const std::string &label, MeshBlockData<T> &src, const std::ve
 
 Two simple examples of usage of these new containers are 1) to provide storage for multistage integration schemes and 2) to provide a mechanism to allocate storage for right hand sides, deltas, etc.  Both of these usages are demonstrated in the advection example that ships with Parthenon.
 
-Note that in multistage integrator the fluxes and `bvars` of a variable
+Note that in multistage integrator the fluxes and `bvars` (and their MPI communicator) of a variable
 are shared by default across all stages.
+This means that any kind of communication (most prominently flux correction and ghost zone
+exchange) of a given variable at a given stage should not be interleaved with any other
+modifications/communication of said variable as it may result in undefined behavior.
```
Comment (Yurlungur) [inline docs/interface/state.md:147]: We can send and then modify before receiving right? Although obviously you probably don't want to do that.

File: src/bvals/bvals_base.cpp [hunk 4]
```diff
@@ -272,22 +273,23 @@ int BoundaryBase::FindBufferID(int ox1, int ox2, int ox3, int fi1, int fi2) {
...
-//              TAG_BITS_PHYS=5, MAX_NUM_PHYS=31
-
-int BoundaryBase::CreateBvalsMPITag(int lid, int bufid, int phys) {
-  return (lid << 11) | (bufid << 5) | phys;
+int BoundaryBase::CreateBvalsMPITag(int lid, int bufid) {
+  PARTHENON_REQUIRE_THROWS(lid >= 0 && bufid >= 0, "Ids are expected to be positive.")
+  int tag = (lid << 6) | bufid;
+  // Technically we could query MPI_TAG_UB here. However, using a fixed (lower) bound
+  // guaranteed by the standard for now to reduce the additional functions calls or
+  // adding a new internal upper lim variable.
```
Comment (Yurlungur) [inline src/bvals/bvals_base.cpp:290]: I am in favor of just using the standard-guaranteed value forever. This is better for portability. Otherwise I can imagine the code dying on some machines and not others...

File: src/interface/variable.cpp [hunk 5]
```diff
@@ -180,18 +187,19 @@ void CellVariable<T>::AllocateFluxesAndBdryVar(std::weak_ptr<MeshBlock> wpmb) {
     }
 
     if (IsSet(Metadata::FillGhost)) {
+      // Ensure data of boundary variable points to the newly allocated data.
       vbvar->Reset(data, coarse_s, flux);
 
+      // TODO(someone): double check if following todo is still applicable with the
+      // "restrict-in-one" machinery. The original code added `vbvar` to
+      // `pmb->pbval->bvars`, but we already do this in the constructor. Also, we
+      // potentially don't iterate over `bvars` any more in the "restrict-in-one" case.
```
Comment (Yurlungur) [inline src/interface/variable.cpp:196]: `RestrictBoundaries` is called per meshblock because the physical boundary condition machinery is still per-meshblock. We need to move the boundary stuff to be "in-one" for this to TODO to become non-relevant.

File: src/mesh/mesh.cpp [hunk 6]
```diff
@@ -485,6 +478,11 @@ Mesh::Mesh(ParameterInput *pin, ApplicationInput *app_in, Packages_t &packages,
 
   mesh_data.SetMeshPointer(this);
 
+  resolved_packages = ResolvePackages(packages);
```
Comment (Yurlungur) [inline src/mesh/mesh.cpp:481]: oops good catch

**Comment by pgrete** [comment]
One more comment/conundrum regarding the failing regression test on Spock #659

The `regression_mpi_test:output_hdf5` currently passes with `develop` but it still fails with this PR.
I just confirmed this in a single session (same node) with fresh binaries.
Even the "conserved" quantity is off, see `advection_3d.hst` of the regression test (third column)
```
  #  History data
  # [1]=time     [2]=dt       [3]=total_advected[4]=max_advected[5]=min_advected
    0.00000e+00  4.68750e-03  1.39160e-02  1.00000e+00  0.00000e+00
    2.53125e-01  4.68750e-03  1.39160e-02  9.38903e-01  0.00000e+00
    5.01563e-01  4.68750e-03  1.39160e-02  7.44601e-01  6.35003e-16
    7.54687e-01  4.68750e-03  1.39160e-02  5.89906e-01  1.27520e-09
    1.00000e+00  3.12500e-03  1.39275e-02  4.80914e-01  1.45889e-07
```
So I'm now wondering if there's sth else we're missing (here).

**Comment by pgrete** [comment]
Update: `develop` is also broken (just in a slightly different way).
Running the test code for longer results in 
```
cycle=288 time=1.3499999999999928e+00 dt=4.6874999999999998e-03 zone-cycles/wsec_step=4.06e+06 wsec_total=1.14e+01 wsec_step=2.31e-02 zone-cycles/wsec=3.84e+06 wsec_AMR=1.36e-03
terminate called after throwing an instance of 'std::runtime_error'
  what():  ### PARTHENON ERROR
  Condition:   !pvar_cc->IsAllocated()
  Message:     FinishRecvSameLevel: Received variable that was not allocated on sending block but it is allocated on receiving block
  File:        /ccs/home/pgrete/src/parthenon/src/mesh/amr_loadbalance.cpp
  Line number: 1313
```
in both cases. So sth is definitely off with MPI comm (and may or may not be system/env dependent).

**Comment by Yurlungur** [comment]
Oof. I guess we should figure out what's going on here before merge. I also still need to run it through Phoebus to see if that breaks anything... though if `develop` is broken, it probably will.

File: src/mesh/mesh.cpp [hunk 7]
```diff
@@ -1050,8 +1053,10 @@ void Mesh::Initialize(bool init_problem, ParameterInput *pin, ApplicationInput *
     // Create send/recv MPI_Requests for all BoundaryData objects
     for (int i = 0; i < nmb; ++i) {
       auto &pmb = block_list[i];
+      // TODO(mpi people) do we still need the pbval part? Discuss also in the context of
+      // other than cellvariables, see comment above on communicators.
```
Comment (Yurlungur) [inline src/mesh/mesh.cpp:1057]: Is there any non-"in one" communication we still do?

**Review by Yurlungur — COMMENTED** [review]
Overall looks reasonable to me, but I want to run it through phoebus and understand what is causing the tests to fail before merge.

**Comment by pgrete** [comment]
> Oof. I guess we should figure out what's going on here before merge. I also still need to run it through Phoebus to see if that breaks anything... though if develop is broken, it probably will.

> Overall looks reasonable to me, but I want to run it through phoebus and understand what is causing the tests to fail before merge.

Are you referring to the failed tests on Spock? I'm still not sure what's going on there but I was not able to reproduce the issue anywhere else so far.
Given that current `develop` has clear bugs (tags, `vbars`, and index) that are all (hopefully) fixed here, my preference is to merge this first and then tackle the other issues #659 #668

File: docs/interface/state.md (hunk 3 above)
Comment (pgrete) [reply docs/interface/state.md:147]: It all depends on the driver design (and how the tasks are ordered in one or more task regions).
My intention with this comment was that people should be really mindful with the async nature of tasks in combination with a shared data (flux, coarse, ghost zone buffers) across stages/containers of a single variable.

File: src/bvals/bvals_base.cpp (hunk 4 above)
Comment (pgrete) [reply src/bvals/bvals_base.cpp:290]: Technically `MPI_TAG_UB` should provide the right info for the given MPI lib at compile time.
Practically, I'm also in favor of keeping the hard coded limit for now until this actually becomes an issue.

**Comment by Yurlungur** [comment]
> Given that current develop has clear bugs (tags, vbars, and index) that are all (hopefully) fixed here, my preference is to merge this first and then tackle the other issues https://github.com/lanl/parthenon/issues/659 https://github.com/lanl/parthenon/issues/668

That works for me. I'll try running a test with Phoebus today.

File: src/mesh/mesh.cpp (hunk 7 above)
Comment (pgrete) [reply src/mesh/mesh.cpp:1057]: If I understood your comment above correctly then `RestrictBoundaries` may be the last place.
However, as far as I can tell the following line can independently be removed because the `vbar` ctor already enlists the `vbars` in the `pbval` list.

Comment (Yurlungur) [reply src/mesh/mesh.cpp:1057]: That seems reasonable.

**Comment by Yurlungur** [comment]
I ran a 2d blast wave in Phoebus with the updated machinery, and 24 MPI ranks. Things seemed to work just fine. Might be good to run a more strenuous test such as a radiation test though, if @brryan or @lroberts36 feel up to it.

**Review by Yurlungur — APPROVED** [review]
Since the updated machinery seems to not break Phoebus's integration, I'm calling this good.

**Comment by pgrete** [comment]
@brryan or @lroberts36 do you also want to give this PR another look before merging?

File: src/bvals/bvals_base.cpp [hunk 8]
```diff
@@ -272,22 +273,23 @@ int BoundaryBase::FindBufferID(int ox1, int ox2, int ox3, int fi1, int fi2) {
...
-// TODO(felker) Consider adding safety check: if (tag > MPI_TAG_UB) PARTHENON_FAIL();
-// TODO(felker) Consider adding safety check: signed int inputs & outputs are positive
-// TODO(felker) Store # of bits for each bitfield component in preprocessor macros
-//              TAG_BITS_PHYS=5, MAX_NUM_PHYS=31
-
-int BoundaryBase::CreateBvalsMPITag(int lid, int bufid, int phys) {
-  return (lid << 11) | (bufid << 5) | phys;
+int BoundaryBase::CreateBvalsMPITag(int lid, int bufid) {
+  PARTHENON_REQUIRE_THROWS(lid >= 0 && bufid >= 0, "Ids are expected to be positive.")
+  int tag = (lid << 6) | bufid;
```
Comment (lroberts36) [inline src/bvals/bvals_base.cpp:287]: Should we be saving more bits for the `bufid` now that there are no physics bits?

File: src/mesh/mesh.hpp [hunk 9]
```diff
@@ -212,6 +212,11 @@ class Mesh {
   // size of default MeshBlockPacks
   int default_pack_size_;
 
+#ifdef MPI_PARALLEL
+  // Global map of MPI comms for separate variables
+  std::map<std::string, MPI_Comm> mpi_comm_map_;
```
Comment (lroberts36) [inline src/mesh/mesh.hpp]: Maybe should be `unordered_map`, although I doubt it matters.

**Review by lroberts36 — APPROVED** [review]
LGTM. I also have this merged into #663.

File: src/bvals/bvals_base.cpp (hunk 8 above)
Comment (pgrete) [reply src/bvals/bvals_base.cpp:287]: I don't think this is required at the moment as we have a max. of 57 buffers globally.

File: src/mesh/mesh.hpp (hunk 9 above)
Comment (pgrete) [reply src/mesh/mesh.hpp]: I had a misplaced `const` that did nothing and I am about to fix. Will update this at the same time.

**Comment by pgrete** [comment]
Thanks for double checking with Phoebus. Pulling the trigger now so that `develop` works again (pending sparse variables).
